from . import help
from . import start
from . import texts
from . import settings
from . import add_usual_test
from . import check_usual_test
from . import ratings
from . import end_test
from . import myTests
from . import add_sp_test
from . import myData
from . import admin